### ISSUE TITLE
Parallel vs. Arry job question

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#10]
I am writing up scheduler->sge-envars.md

What is the diifference between an array and parallel job? Trying to translate nslots, etc to slurm-ese...

**Comment by hgputnam** [comment]
sge-envars.md is probably going to need some work. According to our friends at Stanford, NSLOTS is equivalent to SLURM_NPROCS but I do not know if the document makes sense as written with R and python examples...

https://srcc.stanford.edu/sge-slurm-conversion

**Comment by HenrikBengtsson** [comment]
What was the resolution on this?

**Comment by hgputnam** [comment]
Oh, that was part of the python/R stuff I wasn't comfortable doing. The solution was you taking it on and it looks like it was all done

**Comment by HenrikBengtsson** [comment]
Ah, I see ... this was about Section 'Environment variables in different languages' in https://ucsf-cbi.github.io/c4/scheduler/sge-envvars.html.
