### ISSUE TITLE
Scheduler docs done as best as I am able.

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#11]
@HenrikBengtsson  these pages really need review. I had to leave out entire sections on array jobs and MPI because I am not at all familiar with these...

**Comment by hgputnam** [comment]
Talking about the scheduler folder....

**Comment by HenrikBengtsson** [comment]
Hey, be light on that close button. I haven't reviewed yet.

**Comment by hgputnam** [comment]
Sorry, my OCD got the better of me...

**Comment by HenrikBengtsson** [comment]
Ok, I see what you mean by having to leave it entire sections; I've added those back to #26 - they're needed
