### ISSUE TITLE
FAQ query

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#13]
@HenrikBengtsson Do we want to leave in the "For QB3 migrants...." verbiage? 
I am tempted to just copy/paste some other HPC site's FAQ since I am not sure what kind of stuff may come up...

**Comment by HenrikBengtsson** [comment]
I can clean out the obvious parts.

I think a safer strategy is to update the FAQ as well go, i.e. start with an as clean slate as possible and then we add entries as they're asked.

**Comment by hgputnam** [comment]
Ok, I will put in some really obvious squeue, scancel etc.
