### ISSUE TITLE
Use 'alice' everywhere

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#14]
@hgputnam, I just updated `make check` to scan for our personal usernames in the Markdown files.  This means that Github Actions should now pick such mistakes up and send an email to the one who committed the mistake.  For example, GA now reports on things such as https://github.com/UCSF-CBI/c4/runs/1597628094?check_suite_focus=true#step:3:37;

```sh
./scheduler/job-summary.md:15:cp /c4/home/hputnam/data/CM-0828.aligned.deduplicated.sorted.bam /scratch/$SLURM_JOB_USER/$SLURM_JOB_ID/
...
```

Make sure you update to `hgputnam` to `alice` here.

I know it can be tedious.  This is actually one reason for running tests from the `alice` account; then you get this correct and you know you're testing on a vanilla account.

**Comment by hgputnam** [comment]
Yeah, I've been trying to do that as I go but seem to have missed a couple. Can you add a david to that test so I can use a different test user? Don't want to mess up yours...

**Comment by hgputnam** [comment]
NVR, mind I see you want alice to be consistent in the docs...
