### ISSUE TITLE
Merge failing on my local repo

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#16]
```
hputnam@ubuntu:~/repositories/C4$ git pull origin master
From github.com:/UCSF-CBI/C4
 * branch            master     -> FETCH_HEAD
Auto-merging docs/scheduler/job-summary.md
Auto-merging docs/about/join.md
CONFLICT (content): Merge conflict in docs/about/join.md
Automatic merge failed; fix conflicts and then commit the result.
```

How do I find the conflicts?

**Comment by HenrikBengtsson** [comment]
It happened because I edited `docs/about/join.md` and then committed and pushed, while you've been editing the same original version that I edited in between.  If you open `docs/about/join.md` in the editor, you'll find "merge-conflict" sections of format:

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<
...
=========
...
>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

You need to manually fix what you want within those until you have a "good" document again.  After you've edited the CONFLICT:ed file(s), then call:

```
$ git commit -a
```

After this, you should be able to push.

FWIW, when I use Emacs, those sections are highlighted in colors.

**Comment by HenrikBengtsson** [comment]
I'll hold back for a couple of hours - won't do more edits until you're done for today.

**Comment by hgputnam** [comment]
I think I've completely wedged myself:
```
hputnam@ubuntu:~/repositories/C4$ git commit docs/about/join.md 
fatal: cannot do a partial commit during a merge.
```
I should probably delete my repo and start over, the changes in question are very minor.

**Comment by hgputnam** [comment]
Oh wat a sec, I missed the -a ..

**Comment by hgputnam** [comment]
OK, I *think* it's OK? I hope I did not mess up the master...

**Comment by HenrikBengtsson** [comment]
The first rule of Fight Club is ... whatever you do never ever do a `git push --force`.  Everything else is allowed.

**Comment by hgputnam** [comment]
OK, I will keep that in mind. This is probably a good time to ask what we need to do in order to get the docs site published? Recognizing we will be continuously improving it....

**Comment by HenrikBengtsson** [comment]
Don't see anything in https://github.com/UCSF-CBI/c4/commits/master  - did you forgot to push?

**Comment by hgputnam** [comment]
Yep, I just did so...

**Comment by hgputnam** [comment]
Ugh, and also frogot the make check. Let me fix the usernames... I have to do something for Dave Q for an hour or so but I will get back to it.

**Comment by HenrikBengtsson** [comment]
Looks good to me.

As you might have noticed, git managed to auto-merge lots of things, i.e. both you and I worked on the same files at the same time and it managed to merge our edits in most places.  It's only where we edited the same lines where it struggles.  Then it reports it as a merge conflict and you have to resolve it manually.  (There are also options for accepted what's already available, e.g. `git pull -X theirs`).

I won't do any edits until your done.
