### ISSUE TITLE
BASH: $(date +%s) instead of legacy `date +%s`

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#17]
I suspect you've got some of the examples for the Slurm docs/website.  Let's use the Bash standard:

```sh
today=$(date +%s)
```

rather than the dated:

```sh
today=`date +%s`
```

I can fix this later; I just wanted to make you aware of the `$(...)` syntax, cf. https://github.com/koalaman/shellcheck/wiki/SC2006

**Comment by hgputnam** [comment]
Sorry, the back tick thing goes back to my IRIX days... I will use the $() approach...

**Comment by HenrikBengtsson** [comment]
Absolute no worries; I only switch over fairly recently myself

**Comment by HenrikBengtsson** [comment]
Found these remaining cases:

```sh
$ grep -F '=`' -r --include="*.md"
scheduler/job-summary.md:mysum=`md5sum /c4/home/alice/temp/dummy.bam`
scheduler/job-summary.md:mysum=`md5sum /c4/home/alice/temp/dummy.bam`
scheduler/sge-envvars.md:mydate=`date`
scheduler/sge-envvars.md:full_env=`env|sort`
```

**Comment by hgputnam** [comment]
Believe I got them all.`$ grep -F '=`' -r --include="*.md"` returns nothing.
