### ISSUE TITLE
More stray personal information

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#19]
I've updated the checks to also detect:

```
RESULT: 53 OK, 2 ERROR
/tmp/hb/tmp.X3DCgC8FHg/stdout
./scheduler/job-summary.md:36:#SBATCH --mail-user=harry.putnam@ucsf.edu  # Where to send mail 
./scheduler/sge-envvars.md:34:#SBATCH --mail-user=harry.putnam@ucsf.edu          # user to receive notification emails
Makefile:159: recipe for target 'check-usernames' failed
```

**Comment by hgputnam** [comment]
replaced 'harry.putnam' with 'alice.testuser'

**Comment by HenrikBengtsson** [comment]
`alice.bobson@ucsf.edu` per https://ucsf-cbi.github.io/c4/scheduler/email-notifications.html

**Comment by HenrikBengtsson** [comment]
Actually, I think it should be left it out all along, because it makes the job script include information for a specific person/user.  Imagine if another user copies this job script and the run it as-is - the original user will start getting email notifications for jobs they don't run.  ... and, yeah, there's lots of cut'n'paste and copying taking place without looking into the details what is copied.

**Comment by HenrikBengtsson** [comment]
The best solution if we can configure Unix and/or Slurm to look infer the default email address from LDAP.

**Comment by hgputnam** [comment]
Interesting, challenge accepted, let me mess around with that. I can think of an easy way to do that with bash + ldapsearch. Maybe we can put that in our prolog... I will check to see if there is a configurable option...

**Comment by HenrikBengtsson** [comment]
Resolved; remaining task is in https://github.com/UCSF-TI/C4-sysadm/issues/206
