### ISSUE TITLE
Don't use absolute paths in job scripts

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#22]
In order for scripts to be able to run anywhere without having to edit them, it's important to avoid assumptions about folder structures and never use absolute paths.

If paths are required, paths _relative_ to the current working directory is much better, e.g. `cp data/some_file.txt "$TMPDIR"`.

If absolute paths are required, then use paths relative to user's home directory, e.g.  `cp ~/data/some_file.txt "$TMPDIR"`.

The goal is to write scripts that run anywhere, e.g. on the user's local Linux computer or on Wynton HPC.

A good rule of thumb that there should be no `/c4/home` or `/c4/scratch` paths in example code.

* [x] https://ucsf-cbi.github.io/c4/scheduler/job-summary.html makes use of such absolute paths.

* [x] The script on that page makes assumptions about `/scratch/$SLURM_JOB_USER/$SLURM_JOB_ID`, which the user most likely won't have on their local computer and it won't exist on a SGE environment. So, running it there will cause it to fail. It should use `$TMPDIR`.

**Comment by hgputnam** [comment]
I removed from the job-summary page. If I see any more, I will take them out...

**Comment by HenrikBengtsson** [comment]
There's more in:

* [x] https://ucsf-cbi.github.io/c4/software/singularity.html

**Comment by hgputnam** [comment]
Are they OK in an output example?

**Comment by HenrikBengtsson** [comment]
> Are they OK in an output example?

Yes.  That's out of our and user's control.

**Comment by HenrikBengtsson** [comment]
I think I've removed all absolute paths.
