### ISSUE TITLE
Ruby: How to get environment variable?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#34]
At the bottom of https://ucsf-cbi.github.io/c4/scheduler/envvars.html we have Bash, Python, and R examples on how to get the numeric value of environment variable `SLURM_NPROCS`, e.g.

```python
import os
nslots = os.getenv('SLURM_NPROCS', '1')  # env var is always a 'str'
nslots = int(nslots)                     # coerce to 'int'
print('Number of slots available: ' + nslots)
```

@AaronHechmer / @graft, as our Ruby experts, what's a corresponding example for Ruby?

**Comment by graft** [comment]
You may use `ENV['VAR_NAME']`; it is a global constant.

**Comment by HenrikBengtsson** [comment]
Thxs. And how do you coerce that string into an integer and assign it to a local variable. I  know ~0.1% Ruby

**Comment by HenrikBengtsson** [comment]
...and print a message that includes that parsed integer?

**Comment by graft** [comment]
Sorry, I was sans keyboard earlier. A more complete example:

```

nslots = (ENV['SLURM_NPROCS'] || 1).to_i
puts "Number of slots available: #{nslots}"

```

**Comment by HenrikBengtsson** [comment]
Thank you.  I've add it to https://ucsf-cbi.github.io/c4/scheduler/envvars.html.  Like for the other languages, I took the freedom the split it up into one line per "step" to make it more clear what is happening in each step.

**Comment by AaronHechmer** [comment]
As somebody who grew up just south of Montreal, I'm delighted to see "sans" used here, a useful addition to English along with "faire du shopping," "faire du peepee" and "pamplemousse." However, sans keyboard? That leaves a number of open questions. I'm surprised you saw the thread at all! But you saw the thread and had no keyboard? This happened to me once when Xingyue was babe. I left the room for thirty seconds and she dumped a bottle of pumped breast milk on the laptop keyboard. Was a couple days before I had a replacement keyboard in hand.

I'd hardly call myself a Ruby expert, but I still like it better than python and have the documentation bookmarked: https://ruby-doc.org/

________________________________________
