### ISSUE TITLE
DOCS: Internet access on compute nodes

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#36]
1. The warning box on https://ucsf-cbi.github.io/c4/transfers/files-and-directories.html incorrectly claims that there's no internet access on compute nodes:

> Compute nodes have no internet access, i.e. they cannot be used for file transfers other than between mount points. Although file transfers can also be done via the login nodes, it is recommended to use one of the dedicated data transfer nodes, which provides ten times faster transfer rates.

2. The overview table on https://ucsf-cbi.github.io/c4/about/specs.html also claims there's no internet access on compute notes.

> Outbound access: no

**Comment by hgputnam** [comment]
Do you want to lock down the compute nodes or change the documents?

**Comment by HenrikBengtsson** [comment]
Change docs

**Comment by hgputnam** [comment]
Docs updated
