### ISSUE TITLE
Did my wynton -> c4 edits got undone?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#4]
@hgputnam asked:

> It looks like a bunch of old stuff crept back in to docs that I had previously completed. specs.md for instance now says wynton everywhere instead of c4. Pretty sure I had changed all that but, again, don't know enough github to look at what changed & when...

You can use `git blame` to see when something changed.  You can also do this on the GitHub webpage;

1. Go to the file you wanna look at, e.g. https://github.com/UCSF-CBI/c4/blob/master/docs/about/specs.md

2. Click the 'Blame' button, which will take you to https://github.com/UCSF-CBI/c4/blame/master/docs/about/specs.md

3. Go to the line or lines you're interested in, e.g. https://github.com/UCSF-CBI/c4/blame/master/docs/about/specs.md#L89

4. Then you'll see who edited that line and what the commit message was.

5. You can also look at previous edits on that particular line by clicking on the "View blame prior to this commit" icon, which looks like stacked squared (`||[ ]`).  Clicking on that for Line 89, will take you do https://github.com/UCSF-CBI/c4/blame/19294f609a7219ecbbb6452e68d26724742b95cf/docs/about/specs.md.

As you see, those lines were edited 8 months ago and always had `/wynton/...` paths.

**Comment by hgputnam** [comment]
I must not have committed them. I guess I will have to start over and check them all.
