### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by diazlab** [UCSF-CBI/c4#47]
the link for the C4 issues forum is listed as https://github.com/UCSF-CBI/c4-help/issues on https://ucsf-cbi.github.io/c4/support/index.html , but it should be https://github.com/UCSF-CBI/c4/issues

**Comment by HenrikBengtsson** [comment]
That link is actually correct.  We have a (private) issue tracker for Q&A, feature requests etc at <https://github.com/UCSF-CBI/c4-help/issues>.  The issue tracker you used here is for the website, which you can use for suggesting edits, typos, new example snippets, etc.

**Comment by HenrikBengtsson** [comment]
@diazlab, I've sent you an invite to that issue tracker.  After you accept that you should have access.

**Comment by diazlab** [comment]
Thanks!
