### ISSUE TITLE
rsync proxy?

### ISSUE THREAD

**Issue by diazlab** [UCSF-CBI/c4#48]
I'm having trouble using rsync to transfer data from UC Davis

[aaron@c4-log1 slurm]$ rsync -avL slimsdata.genomecenter.ucdavis.edu::slims/3j4gzd3hjq .
bad response from proxy -- HTTP/1.1 403 Forbidden
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

it works on my laptop, wget works too

**Comment by HenrikBengtsson** [comment]
Please repost on https://github.com/UCSF-CBI/c4-help/issues.  Thxs.
