### ISSUE TITLE
Mistakenly reverted password change page to static

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#5]
I forgot the variables were working and made howto->password change static. I don't know enough github to roll back, etc.

**Comment by HenrikBengtsson** [comment]
You want to undo https://github.com/UCSF-CBI/c4/commit/7480f53306927c7ff56909e2e74500b868bf3cb3#diff-cefb98c23654185569b0654bd9189520b2e688a0ed1dd3499502c6734efc48fd?

**Comment by hgputnam** [comment]
Let me just put the variables back in and re-commit. I changed a bunch of other stuff too...

**Comment by hgputnam** [comment]
Fixed. Thanks @HenrikBengtsson
