### ISSUE TITLE
C4 cluster

### ISSUE THREAD

**Issue by sookwah-yee** [UCSF-CBI/c4#51]
Hi @HenrikBengtsson,
When I try to use the Development nodes this morning, I get something below.  What does this mean and if I did something wrong?

[syee12@c4-log1 ~]$ ssh c4-dev1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:vbbBjuHNZIarjzH4NM+X6GrKRo5oxq+E6abj8LIlFeo.
Please contact your system administrator.
Add correct host key in /c4/home/syee12/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /c4/home/syee12/.ssh/known_hosts:2
ECDSA host key for c4-dev1 has changed and you have requested strict checking.
Host key verification failed.

**Comment by HenrikBengtsson** [comment]
Hi, this is the issue tracker for the website, not for user support.

Please see https://ucsf-cbi.github.io/c4/support/index.html for where to go.
