### ISSUE TITLE
Please review freecycle and updated password docs

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#54]
https://github.com/UCSF-CBI/c4/blob/master/docs/scheduler/freecycle.md

https://github.com/UCSF-CBI/c4/blob/master/docs/howto/change-pwd.md

I will add a frecycle item to the dropdown when we are satisfied.

**Comment by HenrikBengtsson** [comment]
Since we already set the default for `--mail-user`, do we really need to mention that there too?  If we do, we should just point to https://ucsf-cbi.github.io/c4/scheduler/email-notifications.html to minimize redundancy.

PS. FYI GitHub Actions now reports on spelling and Markdown errors

**Comment by hgputnam** [comment]
My local make check quit working. Doesn't all that stuff come automatically when I do a pull?

**Comment by HenrikBengtsson** [comment]
Yes, GitHub sends you email notifications when you `git push` and tests fails.

**Comment by hgputnam** [comment]
Yeah, I get those. Before I was able to run make check on this repo on my Linux vm and it would catch that sort of thing before I pushed. It now complains there is no spelling module.

**Comment by hgputnam** [comment]
I am having a hard time adding the special characters, Markdown is coughing up a hariball on them:
```
!@#$%^&*_-+=`|\(){}:;"'<>,.?/
```

My md previewer shows them all together but the web page has a bunch of spaces just after the backtick. I tried escaping with \

**Comment by HenrikBengtsson** [comment]
> Doesn't all that stuff come automatically when I do a pull?

Now I understand. No, the `make check` toolchain is something you need to maintain locally yourself, cf. https://github.com/UCSF-CBI/c4/#readme

**Comment by HenrikBengtsson** [comment]
> ```
> !@#$%^&*_-+=`|\(){}:;"'<>,.?/
> ```

Try by first adding a space between them, then use the 'Preview' here on GitHub to add them one by one to narrow in on the ones that causes problems.  The backtick is definitely one of them, so save that one for last. There are ways to escape all symbols in Markdown - it's just a matter of figuring out (I often have to search the interwebs for some of them)

**Comment by hgputnam** [comment]
Putting them in a "code box" worked.

**Comment by hgputnam** [comment]
Removed --mail-user section from freecycle.md
