### ISSUE TITLE
Password page

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#55]
On https://github.com/UCSF-CBI/c4/blob/master/docs/howto/change-pwd.md, there is:

* At least three of the following four categories:
  - Lowercase letter
  - Uppercase letter
  - Number
  - Special character.

Two comments:

* Replace 'Number' with 'Digit'
* What are the "special character"?  Adding a `among ! & # ...` would clarify this

**Comment by hgputnam** [comment]
Updated.
