### ISSUE TITLE
How to update data for specs.md?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4#9]
@hgputnam asked:

> Beegfs storage numbers are inaccurate. Not sure where those variables are set. Should be
>
> /c4/home = 196TiB
> /c4/scratch = 240 TiB

If you look at the underlying Markdown for this page (https://ucsf-cbi.github.io/c4/about/specs.html), i.e. https://raw.githubusercontent.com/UCSF-CBI/c4/master/docs/about/specs.md, you'll see:

```md
 * `/c4/home`: {{ site.data.specs.home_size_total }} TiB storage space
 * `/c4/group`: {{ site.data.specs.group_size_total }} TB (= {{ site.data.specs.group_size_total | divided_by: 1000.0 }} PB) storage space
```

That `{{ ... }}` syntax is pre-compiler syntax which pulls in data from a YAML tree:

```
+ site
  +-- data
      +-- specs
          +-- home_size_total
          +-- group_size_total
```

The full `site` YAML tree contains more than this.  The data are pulled in from a few files:

1. [docs/_config.yml](https://github.com/UCSF-CBI/c4/blob/master/docs/_config.yml)
    - everything directly under `site`, i.e. `site.*`
2. [docs/_data/specs.yml](https://github.com/UCSF-CBI/c4/blob/master/docs/_data/specs.yml)
    - everything under `site.data.specs`

In your case, the info you wish to update is in the `docs/_data/specs.yml` file at:

https://github.com/UCSF-CBI/c4/blob/c9ce4ba3abead86e9d63ff1978453f44e1ce6317/docs/_data/specs.yml#L33-L40

**Comment by hgputnam** [comment]
Got it, thanks.
